services:
  - type: web
    name: tophair-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: tophair-db
          property: connectionString
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false

  - type: web
    name: tophair-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://tophair-backend.onrender.com
